version: "3.7"

networks:
  internal:
    driver: bridge

services:
  php:
#    image: php:fpm-alpine
    build: ./docker/php
    container_name: docker.php
    depends_on:
      - mysql
    networks:
      - internal
    volumes:
      - ./app/public_html:/var/www/public_html/
      - ./logs/php.log:/var/log/fpm-php.www.log

  nginx:
    #    image: nginx:alpine
    build: ./docker/nginx
    container_name: docker.nginx
    depends_on:
      - php
    ports:
      - "80:80"
    networks:
      - internal
    volumes:
      - ./app/public_html:/var/www/public_html/
      - ./logs/nginx:/var/log/nginx/

  mysql:
    image: mysql:5
    restart: unless-stopped
    container_name: docker.mysql
    tty: true
    ports:
      - "3306:3306"
    networks:
      - internal
    volumes:
      - "./docker/mysql/mysql.cnf:/etc/mysql/conf.d/custom.cnf:ro"
      - "./docker/mysql/dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-development}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysql}
      MYSQL_USER: ${MYSQL_USER:-mysql}

  phpmyadmin:
    image: phpmyadmin
    container_name: docker.phpmyadmin
    tty: true
    depends_on:
      - mysql
    ports:
      - "8080:80"
    networks:
      - internal
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
      PMA_PORT: 3306
